version: '3.3'
services:
  web:
    build: 
     context: ./php
     dockerfile: Dockerfile.yml
    container_name: php_72
    depends_on: 
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: mysql8 
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: demo
      MYSQL_USER: root1
      MYSQL_PASSWORD: pass
    ports:
      - 85:3306        
